server:
  ip: localhost
  port: 8080

spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.8.242:3306/db_myserver?characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Lovechen6@
  redis:
    host: 192.168.8.242
    username: root
    password: lovechen66
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: /Users/wanghuachen/Downloads/files
